# This is a basic workflow to help you get started with Actions
name: CI
  
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  clean-and-test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.10', '3.11']
    steps:
    - name: Run linter
      run: |
        python -m pip install --upgrade pip
        cd ../..
        echo $PWD
        pip install -r requirements.txt
        echo "Dependencies has been installed."
        flake8